trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


# File transform
# Replace tokens with variable values in XML or JSON configuration files
# task: FileTransform@2
  #inputs:
     #folderPath: '$(Build.ArtifactStagingDirectory)' 
    #enableXmlTransform: # Optional
    # xmlTransformationRules: '-transform **\*.Production.config -xml **\*.config'
    #fileType: # Optional. Options: xml, json
    #targetFiles: # Optional
# File transform
# Replace tokens with variable values in XML or JSON configuration files
#- task: FileTransform@1
  #inputs:
    #folderPath: '$(Build.ArtifactStagingDirectory)' 
    #enableXmlTransform: # Optional
    #xmlTransformationRules: '-transform **\*.<stage>.config -xml **\*.config-transform **\*.$(<stage>.EnvironmentName).config -xml **\*.config' # Optional
    #fileType: # Optional. Options: xml, json
    #targetFiles: # Optional
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

